{% set name = "crocoddyl" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/loco-3d/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: b861424d2725b63306878bb37ee407f6f07412ef82d27fba25a3604c2c7b725d

build:
  number: 2
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pinocchio                              # [build_platform != target_platform]
  host:
    - eigen
    - eigenpy
    - pinocchio
    - boost
    - python
    - example-robot-data
    - numpy  # [build_platform != target_platform]
  run:
    - eigen
    - eigenpy
    - pinocchio
    - boost
    - python
    - example-robot-data
    - {{ pin_compatible('numpy') }}  # [build_platform != target_platform]

test:
  requires:
    - pkg-config
  commands:
    - pkg-config --modversion {{ name }}
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
  imports:
    - crocoddyl

about:
  home: http://github.com/loco-3d/crocoddyl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Crocoddyl is an optimal control library for robot control under contact sequence. Its solver is based on various efficient Differential Dynamic Programming (DDP)-like algorithms.
  dev_url: https://github.com/loco-3d/crocoddyl

extra:
  recipe-maintainers:
    - jcarpent
